using RevitPlugin.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RevitPlugin.Helper.TimeZone
{
    public static class TimeZone
    {
        public static Dictionary<string, string> TimeZoneToContinent = new Dictionary<string, string>
        {
            {"Dateline Standard Time", "OC"},
            {"UTC-11", "OC"},
            {"Aleutian Standard Time", "NA"},
            {"Hawaiian Standard Time", "NA"},
            {"Marquesas Standard Time", "OC"},
            {"Alaskan Standard Time", "NA"},
            {"UTC-09", "NA"},
            {"Pacific Standard Time (Mexico)", "NA"},
            {"UTC-08", "NA"},
            {"Pacific Standard Time", "NA"},
            {"US Mountain Standard Time", "NA"},
            {"Mountain Standard Time (Mexico)", "NA"},
            {"Mountain Standard Time", "NA"},
            {"Yukon Standard Time", "NA"},
            {"Central America Standard Time", "NA"},
            {"Central Standard Time", "NA"},
            {"Easter Island Standard Time", "SA"},
            {"Central Standard Time (Mexico)", "NA"},
            {"Canada Central Standard Time", "NA"},
            {"SA Pacific Standard Time", "SA"},
            {"Eastern Standard Time (Mexico)", "NA"},
            {"Eastern Standard Time", "NA"},
            {"Haiti Standard Time", "NA"},
            {"Cuba Standard Time", "NA"},
            {"US Eastern Standard Time", "NA"},
            {"Turks And Caicos Standard Time", "NA"},
            {"Paraguay Standard Time", "SA"},
            {"Atlantic Standard Time", "NA"},
            {"Venezuela Standard Time", "SA"},
            {"Central Brazilian Standard Time", "SA"},
            {"SA Western Standard Time", "SA"},
            {"Pacific SA Standard Time", "SA"},
            {"Newfoundland Standard Time", "NA"},
            {"Tocantins Standard Time", "SA"},
            {"E. South America Standard Time", "SA"},
            {"SA Eastern Standard Time", "SA"},
            {"Argentina Standard Time", "SA"},
            {"Montevideo Standard Time", "SA"},
            {"Magallanes Standard Time", "SA"},
            {"Saint Pierre Standard Time", "NA"},
            {"Bahia Standard Time", "SA"},
            {"UTC-02", "UTC"},
            {"Greenland Standard Time", "NA"},
            {"Mid-Atlantic Standard Time", "NA"},
            {"Azores Standard Time", "EU"},
            {"Cape Verde Standard Time", "AF"},
            {"UTC", "UTC"},
            {"GMT Standard Time", "EU"},
            {"Greenwich Standard Time", "EU"},
            {"Sao Tome Standard Time", "AF"},
            {"Morocco Standard Time", "AF"},
            {"W. Europe Standard Time", "EU"},
            {"Central Europe Standard Time", "EU"},
            {"Romance Standard Time", "EU"},
            {"Central European Standard Time", "EU"},
            {"W. Central Africa Standard Time", "AF"},
            {"GTB Standard Time", "EU"},
            {"Middle East Standard Time", "AS"},
            {"Egypt Standard Time", "AF"},
            {"E. Europe Standard Time", "EU"},
            {"West Bank Standard Time", "AS"},
            {"South Africa Standard Time", "AF"},
            {"FLE Standard Time", "EU"},
            {"Israel Standard Time", "AS"},
            {"South Sudan Standard Time", "AF"},
            {"Kaliningrad Standard Time", "EU"},
            {"Sudan Standard Time", "AF"},
            {"Libya Standard Time", "AF"},
            {"Namibia Standard Time", "AF"},
            {"Jordan Standard Time", "AS"},
            {"Arabic Standard Time", "AS"},
            {"Syria Standard Time", "AS"},
            {"Turkey Standard Time", "AS"},
            {"Arab Standard Time", "AS"},
            {"Belarus Standard Time", "EU"},
            {"Russian Standard Time", "EU"},
            {"E. Africa Standard Time", "AF"},
            {"Volgograd Standard Time", "EU"},
            {"Iran Standard Time", "AS"},
            {"Arabian Standard Time", "AS"},
            {"Astrakhan Standard Time", "EU"},
            {"Azerbaijan Standard Time", "AS"},
            {"Russia Time Zone 3", "EU"},
            {"Mauritius Standard Time", "AF"},
            {"Saratov Standard Time", "EU"},
            {"Georgian Standard Time", "AS"},
            {"Caucasus Standard Time", "AS"},
            {"Afghanistan Standard Time", "AS"},
            {"West Asia Standard Time", "AS"},
            {"Ekaterinburg Standard Time", "EU"},
            {"Pakistan Standard Time", "AS"},
            {"Qyzylorda Standard Time", "AS"},
            {"India Standard Time", "AS"},
            {"Sri Lanka Standard Time", "AS"},
            {"Nepal Standard Time", "AS"},
            {"Central Asia Standard Time", "AS"},
            {"Bangladesh Standard Time", "AS"},
            {"Omsk Standard Time", "AS"},
            {"Myanmar Standard Time", "AS"},
            {"SE Asia Standard Time", "AS"},
            {"Altai Standard Time", "AS"},
            {"W. Mongolia Standard Time", "AS"},
            {"North Asia Standard Time", "AS"},
            {"N. Central Asia Standard Time", "AS"},
            {"Tomsk Standard Time", "AS"},
            {"China Standard Time", "AS"},
            {"North Asia East Standard Time", "AS"},
            {"Singapore Standard Time", "AS"},
            {"W. Australia Standard Time", "OC"},
            {"Taipei Standard Time", "AS"},
            {"Ulaanbaatar Standard Time", "AS"},
            {"Aus Central W. Standard Time", "OC"},
            {"Transbaikal Standard Time", "AS"},
            {"Tokyo Standard Time", "AS"},
            {"North Korea Standard Time", "AS"},
            {"Korea Standard Time", "AS"},
            {"Yakutsk Standard Time", "AS"},
            {"Cen. Australia Standard Time", "OC"},
            {"AUS Central Standard Time", "OC"},
            {"E. Australia Standard Time", "OC"},
            {"AUS Eastern Standard Time", "OC"},
            {"West Pacific Standard Time", "OC"},
            {"Tasmania Standard Time", "OC"},
            {"Vladivostok Standard Time", "AS"},
            {"Lord Howe Standard Time", "OC"},
            {"Bougainville Standard Time", "OC"},
            {"Russia Time Zone 10", "EU"},
            {"Magadan Standard Time", "AS"},
            {"Norfolk Standard Time", "OC"},
            {"Sakhalin Standard Time", "AS"},
            {"Central Pacific Standard Time", "OC"},
            {"Russia Time Zone 11", "EU"},
            {"New Zealand Standard Time", "OC"},
            {"UTC+12", "AS"},
            {"Fiji Standard Time", "OC"},
            {"Kamchatka Standard Time", "AS"},
            {"Chatham Islands Standard Time", "OC"},
            {"UTC+13", "OC"},
            {"Tonga Standard Time", "OC"},
            {"Samoa Standard Time", "OC"},
            {"Line Islands Standard Time", "OC"}
        };

        public static string GetContinentCode()
        {
            TimeZoneInfo localTimeZone = TimeZoneInfo.Local;
            if(localTimeZone.IsNotNull())
            {
                return TimeZoneToContinent[localTimeZone.Id];
            }
            return "";

        }
    }
}
